apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: 621715857751.dkr.ecr.us-east-1.amazonaws.com/ecr-repository:v1
        ports:
        - containerPort: 8080
